# -*- coding: utf-8 -*-
"""Asthma_Dashboard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tmTccbaNgt7Sn5EqmBuXDZtutyCUYDi
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Read the CSV file
df = pd.read_csv("asthma-ed-visit-rates-lghc-indicator-07-.csv")

# Function to plot bar chart
def plot_bar_chart(df, column):
    fig = px.bar(df, x=column)
    st.plotly_chart(fig)

# Function to plot pie chart
def plot_pie_chart(df, column):
    fig = px.pie(df, names=column)
    st.plotly_chart(fig)


# Set the app title
st.title("Asthma Data Set Dashboard")

# Display the data set
st.subheader("Data Set")
st.dataframe(df)

# Show descriptive statistics
st.subheader("Descriptive Statistics")
st.write(df.describe())

# Show a bar chart
st.subheader("Bar Chart")
column_to_plot = st.selectbox("Select a Column for Bar Chart", df.columns)
plot_bar_chart(df, column_to_plot)

# Show a pie chart
st.subheader("Pie Chart")
column_to_plot = st.selectbox("Select a Column for Pie Chart", df.columns)
plot_pie_chart(df, column_to_plot)







